// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTRGQMomjeS90Ngh6_U_uqGI2-AeUnAw',
    appId: '1:1090381273033:web:23b46a509581d2496d3a18',
    messagingSenderId: '1090381273033',
    projectId: 'educator-app-308f6',
    authDomain: 'educator-app-308f6.firebaseapp.com',
    storageBucket: 'educator-app-308f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxG9O0IixPAp0Ypda-YxHVnJVmaHWU0U',
    appId: '1:1090381273033:android:dde94b5b330ff9626d3a18',
    messagingSenderId: '1090381273033',
    projectId: 'educator-app-308f6',
    storageBucket: 'educator-app-308f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJn0VxTHEIS5h-e3deOeyLEiI77Vsmqsw',
    appId: '1:1090381273033:ios:ba1b52f5abb5ca8a6d3a18',
    messagingSenderId: '1090381273033',
    projectId: 'educator-app-308f6',
    storageBucket: 'educator-app-308f6.appspot.com',
    iosBundleId: 'com.spt.spt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJn0VxTHEIS5h-e3deOeyLEiI77Vsmqsw',
    appId: '1:1090381273033:ios:3769b7c06e6a58176d3a18',
    messagingSenderId: '1090381273033',
    projectId: 'educator-app-308f6',
    storageBucket: 'educator-app-308f6.appspot.com',
    iosBundleId: 'com.spt.spt.RunnerTests',
  );
}
